// Project data — ported from v1 (/workspace/MyWebsite/js/projects.js).
// Schema: { id, title, summary, thumbnail, iframeUrl, liveUrl, tags, description, github }
//   - iframeUrl: null when the demo is not iframable (X-Frame-Options, no demo, etc.)
//   - liveUrl:   the live destination (set whenever a hosted demo exists, iframable or not)
//   - tags:      conceptual vocabulary; filter buttons are derived from the union
export const projects = [
    {
        id: 'christmas-lights-ai',
        title: 'Christmas Lights AI Demo',
        summary: 'Draw light strands on a photo and watch AI bring them to life.',
        thumbnail: 'https://i.imgur.com/m0Wfsrh.png',
        iframeUrl: 'https://christianblevens.github.io/AddSplineToPictureThenAIWebApp/',
        liveUrl: 'https://christianblevens.github.io/AddSplineToPictureThenAIWebApp/',
        tags: ['AI', 'Web App', 'Tool'],
        description: [
            '- Spline-based light placement with depth-mapped guidance',
            '- Per-strand color, density, glow, and animation controls',
            '- Server-side AI enhancement adds realistic bloom and glow',
            '',
            'Upload or capture a photo, draw light paths along the architecture, and the cloud pipeline (depth + line detection + AI relight) returns a finished holiday-lit image. Built on HTML5 Canvas with touch and mouse parity.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/AddSplineToPictureThenAIWebApp',
    },
    {
        id: 'daily-habits',
        title: 'Daily Habit Tracker',
        summary: 'Log activities against your wake time and watch streaks form.',
        thumbnail: null,
        iframeUrl: '/daily-habits/',
        liveUrl: '/daily-habits/',
        tags: ['Web App', 'Tool'],
        description: [
            '- Streak tracking with weekly performance rates',
            '- Markdown-rich activity entries with tags and sub-tasks',
            '- Today-vs-yesterday and weekly-average comparisons',
            '',
            'A minimalist productivity tracker oriented around your wake-up time. Firebase syncs data across devices and the UI rewards consistency without nagging.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/DailyScheduleWebApp',
    },
    {
        id: 'roof',
        title: 'Roof Area Calculator',
        summary: 'Click a roof on a satellite map and get its square footage.',
        thumbnail: 'https://i.imgur.com/ldkbu25.png',
        iframeUrl: '/roof/',
        liveUrl: '/roof/',
        tags: ['Web App', 'Tool'],
        description: [
            '- Geolocation, address search, or raw coordinate input',
            '- Connected-component pixel detection on satellite imagery',
            '- Area math accounts for zoom level and Earth curvature',
            '',
            'Useful for solar installers, roofers, and property assessors who need a fast estimate without a site visit.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/RoofAreaCalculatorWebApp',
    },
    {
        id: 'sunlight',
        title: 'Sunlight Hours Tracker',
        summary: 'Animated daylight, twilight, and lunar phases for your location.',
        thumbnail: null,
        iframeUrl: '/sunlight/',
        liveUrl: '/sunlight/',
        tags: ['Web App', 'Visualization'],
        description: [
            '- Sunrise, sunset, and three twilight stages with countdowns',
            '- Animated sun and moon positions, hourly moon phase',
            '- Debug time-slider for exploring the full day',
            '',
            'Pulls from Open-Meteo, Farmsense, and OpenStreetMap to render an accurate daily sky for wherever you are. Built for photographers chasing golden hour and anyone curious about local sky cycles.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/SunlightTrackerWebApp',
    },
    {
        id: 'global-time',
        title: 'Global Time & Daylight Comparison',
        summary: 'Stack multiple cities and compare their daylight side by side.',
        thumbnail: null,
        iframeUrl: '/global-time/',
        liveUrl: '/global-time/',
        tags: ['Web App', 'Visualization'],
        description: [
            '- Add any number of locations, each with its own 24-hour bar',
            '- Color-gradient backgrounds reflect live daylight phase',
            '- Live current-time markers update every minute',
            '',
            'Geocodes location names, pulls timezone and solar data, and renders synchronized day/night gradients across every bar. Handy for distributed teams and trip planning.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/TimeAndDayLightComparisonWebApp',
    },
    {
        id: 'gravity-wars',
        title: 'Gravity Wars',
        summary: 'Wave-based space shooter with roguelike ability picks.',
        thumbnail: null,
        iframeUrl: '/gravity-wars/',
        liveUrl: '/gravity-wars/',
        tags: ['Game', 'Web App'],
        description: [
            '- WASD + mouse aim, spacebar dash for repositioning',
            '- Four ability slots unlocked and upgraded between waves',
            '- Combo multiplier rewards aggressive chaining',
            '',
            'A browser arcade shooter where each run lets you cobble together an unusual build. Fast, loud, and built straight on Canvas.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/SpaceBattleGameWebApp',
    },
    {
        id: 'video-editor',
        title: 'AI Video Editor',
        summary: 'Multi-track editor with AI transcription, filler removal, and burn-in subtitles.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Tool', 'Video'],
        description: [
            '- Pause, filler-word, and profanity detection with one-click cleanup',
            '- Word-level subtitles with custom styling and burn-in',
            '- Batched FastAPI backend, ~12.5× faster than real time',
            '- GPU-accelerated FFmpeg export at multiple quality presets',
            '',
            'A complete editing surface that pairs traditional clip work with AI passes that strip out the boring parts. Designed for creators who want to ship faster without giving up control.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/VideoEditor',
    },
    {
        id: 'face-anon',
        title: 'Face Anonymization Pipeline',
        summary: 'Generate one synthetic identity, apply it consistently across video.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Video'],
        description: [
            '- RetinaFace detection with FARL anonymization',
            '- CodeFormer enhancement for realism',
            '- FaceFusion swap to apply the synthetic face to footage',
            '- GPU-accelerated, Docker-deployable end to end',
            '',
            'Solves the cross-clip continuity problem: anonymize a face once, then keep that same identity in place across an entire body of video work.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'word-extractor',
        title: 'YouTube Word Extractor',
        summary: 'Find every utterance of a word across videos and stitch them into a supercut.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Video', 'Tool'],
        description: [
            '- Six-stage pipeline: download, transcribe, search, extract, normalize, compile',
            '- Faster Whisper + CTranslate2 for word-level timestamps',
            '- Cloud cache shares transcriptions across users',
            '- GPU and CPU modes; Docker Compose deployable',
            '',
            'Point it at a video, channel, or playlist and a target word; it returns a ready-rendered compilation. Useful for compilations, research, and supercuts.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/FasterWhisperWebApp',
    },
    {
        id: 'comments',
        title: 'Production Comment System',
        summary: 'Self-hosted Discord-auth comments with AI moderation, drop in via one script tag.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Web App', 'Tool'],
        description: [
            '- Discord OAuth — no password management',
            '- AI spam/toxicity detection plus manual moderation tools',
            '- Markdown comments, voting, reputation scores',
            '- Iframe embed auto-themes to the host site',
            '',
            'A privacy-respecting alternative to third-party comment platforms. Powers the Comments section on this very site (see the top nav).',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/CommentSectionWebApp',
    },
    {
        id: 'portfolio-v1',
        title: 'Portfolio Website (v1)',
        summary: 'The previous version of this site — Alpine + Tailwind + iframe modals.',
        thumbnail: 'https://i.imgur.com/WYd2iPv.png',
        iframeUrl: '/v1/',
        liveUrl: '/v1/',
        tags: ['Web App', 'Personal'],
        description: [
            '- Alpine.js reactive components across eight modules',
            '- PostMessage iframe height-sync for cross-origin demos',
            '- Tailwind styling with overflow-aware filter bar',
            '',
            'The first custom build of christianblevens.me. Archived under /v1/ once the v2 deploy lands; included here for continuity.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/MyWebsite',
    },
    {
        id: 'terrain',
        title: 'Destructible Terrain',
        summary: 'Multiplayer combat where the battlefield gets carved up in real time.',
        thumbnail: 'https://i.imgur.com/I7ZkATK.mp4',
        iframeUrl: 'https://itch.io/embed-upload/8431679?color=333333',
        liveUrl: 'https://itch.io/embed-upload/8431679?color=333333',
        tags: ['Game', 'Multiplayer', '3D'],
        description: [
            '- Voxel terrain destruction synced across all clients',
            '- Fish Networking for authoritative multiplayer state',
            '- Data-oriented design keeps frame times flat under chaos',
            '',
            'Cover stops being permanent. Players carve paths and clear sightlines mid-fight, and the simulation stays consistent across the network.',
        ].join('\n'),
        github: 'https://github.com/christianblevens/terrain-fighter',
    },
    {
        id: 'moba',
        title: 'Unity ECS MOBA',
        summary: 'Full-DOTS MOBA with a mod-safe, runtime-composable ability system.',
        thumbnail: 'https://i.imgur.com/rBJsZzW.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', 'Multiplayer', '3D'],
        description: [
            '- Pure Unity DOTS / ECS — no GameObjects in the gameplay layer',
            '- Mod-safe ability composition, networked deterministically',
            '- Steam Networking for matchmaking and lobbies',
            '',
            'Built to prove that data-oriented design and MOBA gameplay can co-exist without giving up the depth of a traditional ability system.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/UltimateMoba',
    },
    {
        id: 'tiny-home',
        title: 'Tiny Home Design Presentation',
        summary: 'Walk through tiny-home interior layouts in the browser.',
        thumbnail: 'https://i.imgur.com/zW5XWYm.mp4',
        iframeUrl: 'https://itch.io/embed-upload/12942892?color=333333',
        liveUrl: 'https://itch.io/embed-upload/12942892?color=333333',
        tags: ['3D', 'Business'],
        description: [
            '- ProBuilder-built interiors, no external DCC required',
            '- Modular interaction system — open cabinets, toggle features',
            '- Deployed as production WebGL for client presentations',
            '',
            'A first-person walkthrough tool that lets non-technical clients understand a space before construction starts.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'group-pathfinding',
        title: 'Group Pathfinding',
        summary: 'A* for the route, boids for the crowd — large groups that don\'t pile up.',
        thumbnail: 'https://i.imgur.com/9ff2MqU.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', '3D', 'Simulation'],
        description: [
            '- Two-tier: classical pathfinding for plans, boid behaviors locally',
            '- Dynamic clustering reduces per-agent path queries',
            '- Gizmo overlays for nodes, sight lines, and obstacle perception',
            '',
            'Recognizes that moving a hundred units isn\'t the same problem as moving one. Cohesion and avoidance happen between agents while the planner handles the macro route.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'camera-radar',
        title: 'Camera + Radar Tracking',
        summary: 'University capstone: radar detects a target, a servo camera turns to face it.',
        thumbnail: 'https://i.imgur.com/klahjti.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Tool', 'Visualization'],
        description: [
            '- Coordinate transforms tolerate arbitrary radar/camera placement',
            '- Unity-based math validation visualizer prior to hardware deploy',
            '- Web UI for remote operation and parameter tuning',
            '',
            'Bridges sensor fusion math, embedded servo control, and a remote operator console. The visualization tool was essential — it caught coordinate-frame mistakes before they reached the hardware.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'oon-ecs',
        title: 'Object-Oriented Networking ECS',
        summary: 'A pattern that makes ECS systems first-class citizens of OOP networking libraries.',
        thumbnail: 'https://i.imgur.com/Rt6xMLu.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', 'Multiplayer'],
        description: [
            '- Each ECS system is wrapped as a networked object',
            '- Dynamic system-to-entity dispatch preserves DOD performance',
            '- Framework-agnostic — tested with Fish Networking',
            '',
            'Mainstream Unity multiplayer libraries assume you\'re networking objects, not data. This abstraction lets you use those libraries while keeping ECS\'s cache and parallelism wins.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'walkable-pathfinding',
        title: 'Walkable Surface Detection',
        summary: 'Voxel-based 3D pathfinding that finds its own walkable surfaces.',
        thumbnail: 'https://i.imgur.com/voSAMvC.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', '3D', 'Simulation'],
        description: [
            '- Octree physics sampling discovers walkable voxels',
            '- Adjacent-node merging shrinks the navigation graph',
            '- Gizmo visualization of nodes, edges, and detected surfaces',
            '',
            'No artist-authored navmesh required. Handles overhangs, multi-level layouts, and procedurally generated environments where a baked navmesh isn\'t available.',
        ].join('\n'),
        github: null,
    },
    {
        id: '365-lighting',
        title: '365 Holiday Lighting Website',
        summary: 'Wix business site for a Christmas lighting installation company.',
        thumbnail: 'https://i.imgur.com/1llffvH.png',
        iframeUrl: null,
        liveUrl: 'https://www.365holidaylighting.com/',
        tags: ['Web App', 'Business'],
        description: [
            'A no-code build for a real client: services, gallery, contact, and SEO. The right tool for the job — Wix delivered the result faster and cheaper than a custom stack would have.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'old-portfolio',
        title: 'My First Personal Website',
        summary: 'Squarespace portfolio from earlier in my career.',
        thumbnail: 'https://i.imgur.com/TsxhPjO.png',
        iframeUrl: '/old-portfolio/',
        liveUrl: '/old-portfolio/',
        tags: ['Web App', 'Personal'],
        description: [
            'A clean Squarespace site that served as my first online portfolio. Kept around as a milestone — the limitations of template-based platforms are exactly what motivated the custom builds that followed.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'point-attraction',
        title: 'Point Attraction',
        summary: 'Particles with simple attraction/repulsion rules; complex behavior emerges.',
        thumbnail: 'https://i.imgur.com/Hjzf1Ua.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Simulation', 'Visualization'],
        description: [
            '- Per-particle pairwise attraction and repulsion',
            '- Tunable parameters expose how rule shifts change patterns',
            '',
            'A small artistic sandbox for emergence. Reads as fluid one moment, flocking the next — all from a handful of pairwise rules.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'tf2-dodgeball',
        title: 'TF2 Dodgeball Recreation',
        summary: 'A love letter to TF2 dodgeball with Source-style movement and added abilities.',
        thumbnail: 'https://i.imgur.com/UkeeOav.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game'],
        description: [
            '- Source-feel movement — air strafing, rocket jumps, momentum',
            '- Local multiplayer with rally-speed escalation',
            '- New ability set layered on top of the classic deflect mechanic',
            '',
            'Faithful to the mod that inspired it, with just enough new ideas to be its own thing.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'line-physics',
        title: 'Line Physics',
        summary: '2D physics from scratch, drawn as live line segments on canvas.',
        thumbnail: 'https://i.imgur.com/EIKLGGE.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Simulation'],
        description: [
            '- Gravity, velocity, constraints, and collisions, all hand-rolled',
            '- Variable resolution to trade visual fidelity for cost',
            '',
            'No engine physics — just the math. A learning piece that makes the underlying machinery legible.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'life-sim',
        title: 'Life Simulation',
        summary: 'Agents with traits, selection pressure, and generations of drift.',
        thumbnail: 'https://i.imgur.com/GyREhiS.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Simulation'],
        description: [
            '- Spatial partitioning enables thousands of concurrent agents',
            '- Generational tracking of trait distributions',
            '- Query interface for inspecting subpopulations',
            '',
            'A small artificial-life sandbox where successful strategies propagate and unsuccessful ones disappear. Built with array access patterns tight enough to keep the populations large.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'van-build',
        title: 'Van Home Build',
        summary: 'Cargo van conversion — planning, leadership, and a lot of plywood.',
        thumbnail: 'https://i.imgur.com/eXJvpxP.jpeg',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Personal'],
        description: [
            '- Long-form planning across electrical, plumbing, and structure',
            '- CAD models guided every cut and panel',
            '- Coordinated volunteers and budget across a multi-month build',
            '',
            'A real-world project run with the same discipline as a software one. Listed because the soft skills — scoping, decision-making, and seeing it through — are the same ones I bring to engineering work.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'voluhaus',
        title: 'Voluhaus',
        summary: 'AI-powered staging platform — see the room before the truck leaves.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: 'https://voluhaus.com/',
        tags: ['Web App', 'AI', '3D', 'Business'],
        description: [
            '- AI room extraction from a single phone photo',
            '- Drag-and-drop 3D furniture placement against the captured space',
            '- Auto-generated 3D models from photos of inventory',
            '- Inventory scheduling prevents double-booking across stagings',
            '- Shareable before/after presentations for clients',
            '',
            'A complete staging workflow for home-furnishing professionals — capture, plan, schedule, and present, all from a phone.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'random-bookmark',
        title: 'Random Bookmark Selector',
        summary: 'Break decision paralysis — pull a random bookmark out of your saved list.',
        thumbnail: null,
        iframeUrl: '/random-bookmark/',
        liveUrl: '/random-bookmark/',
        tags: ['Web App', 'Tool'],
        description: [
            '- Paste in your bookmark export and get a random pick',
            '- Pure client-side — bookmarks never leave the page',
            '- Built straight on HTML and JS, no backend',
            '',
            'A small utility for rediscovering links you saved months ago and forgot about.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/RandomBookmarkSelector',
    },
    {
        id: 'audio-repositioner',
        title: 'Audio Repositioner',
        summary: 'Spatial audio panning in the browser — move sound through stereo space.',
        thumbnail: null,
        iframeUrl: '/audio-repositioner/',
        liveUrl: '/audio-repositioner/',
        tags: ['Web App', 'Tool', 'Audio'],
        description: [
            '- WebAudio panner controls for left/right and depth',
            '- Drop in any audio file, no upload',
            '- Built directly on the Web Audio API',
            '',
            'A browser-native sandbox for repositioning sound in the stereo field.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/AudioRepositioner',
    },
    {
        id: 'bpd',
        title: 'Behavioral Pattern Discovery',
        summary: 'ML communication analysis — categorize messages by behavior and pattern type.',
        thumbnail: null,
        iframeUrl: '/bpd/',
        liveUrl: '/bpd/',
        tags: ['AI', 'Web App', 'Tool', 'Visualization'],
        description: [
            '- Variational autoencoder learns the latent structure of group conversations',
            '- Categorizes messages into communication and behavior pattern types',
            '- Trained on real message exchanges between a group',
            '- Web interface for exploring the learned categories',
            '',
            'Surfaces the patterns that drive how a group actually talks — useful for self-reflection and for understanding interpersonal dynamics that aren\'t obvious in raw transcripts.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'nginx-manager',
        title: 'Personal Site Infrastructure',
        summary: 'Self-hosted reverse proxy and deployment setup powering this site.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Tool', 'Infrastructure'],
        description: [
            '- Containerized nginx reverse proxy with SSL termination',
            '- Static asset routing with per-project cache policies',
            '- Backend service proxying with rate limiting and health checks',
            '- Drop-in config pattern for adding new projects without downtime',
            '',
            'The plumbing that lets the rest of these projects live under one domain. Private repo — it describes my server\'s internal layout — but it\'s the backbone everything else here runs on.',
        ].join('\n'),
        github: null,
    },
];

// Filter buttons are derived dynamically from the union of all tags so adding
// a new project tag automatically produces a new filter — no manual sync.
export const filters = (() => {
    const seen = new Set();
    for (const p of projects) for (const t of p.tags || []) seen.add(t);
    const tagButtons = [...seen].sort().map(t => ({ id: t, label: t }));
    return [{ id: 'all', label: 'All' }, ...tagButtons];
})();
