// Project data — ported from v1 (/workspace/MyWebsite/js/projects.js).
// Schema: { id, title, summary, thumbnail, iframeUrl, liveUrl, tags, description, github }
//   - iframeUrl: null when the demo is not iframable (X-Frame-Options, no demo, etc.)
//   - liveUrl:   the live destination (set whenever a hosted demo exists, iframable or not)
//   - tags:      conceptual vocabulary; filter buttons are derived from the union
export const projects = [
    {
        id: 'christmas-lights-ai',
        title: 'Christmas Lights AI Demo',
        summary: 'Draw light strands on a photo and watch AI bring them to life.',
        thumbnail: '/assets/thumbs/m0Wfsrh.png',
        iframeUrl: '/christmas-lights/',
        liveUrl: '/christmas-lights/',
        tags: ['AI', 'Web App', 'Tool'],
        description: [
            '- Spline-based light placement with depth-mapped guidance',
            '- Per-strand color, density, glow, and animation controls',
            '- Server-side AI enhancement adds realistic bloom and glow',
            '',
            'Upload or capture a photo, draw light paths along the architecture, and the cloud pipeline (depth + line detection + AI relight) returns a finished holiday-lit image. Built on HTML5 Canvas with touch and mouse parity.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/AddSplineToPictureThenAIWebApp',
    },
    {
        id: 'daily-habits',
        title: 'Daily Habit Tracker',
        summary: 'Log activities against your wake time and watch streaks form.',
        thumbnail: null,
        iframeUrl: '/daily-habits/',
        liveUrl: '/daily-habits/',
        tags: ['Web App', 'Tool'],
        description: [
            '- Streak tracking with weekly performance rates',
            '- Markdown-rich activity entries with tags and sub-tasks',
            '- Today-vs-yesterday and weekly-average comparisons',
            '',
            'A minimalist productivity tracker oriented around your wake-up time. Firebase syncs data across devices and the UI rewards consistency without nagging.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/DailyScheduleWebApp',
    },
    {
        id: 'roof',
        title: 'Roof Area Calculator',
        summary: 'Click a roof on a satellite map and get its square footage.',
        thumbnail: '/assets/thumbs/ldkbu25.png',
        iframeUrl: '/roof/',
        liveUrl: '/roof/',
        tags: ['Web App', 'Tool'],
        description: [
            '- Geolocation, address search, or raw coordinate input',
            '- Connected-component pixel detection on satellite imagery',
            '- Area math accounts for zoom level and Earth curvature',
            '',
            'Useful for solar installers, roofers, and property assessors who need a fast estimate without a site visit.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/RoofAreaCalculatorWebApp',
    },
    {
        id: 'sunlight',
        title: 'Sunlight Hours Tracker',
        summary: 'Animated daylight, twilight, and lunar phases for your location.',
        thumbnail: null,
        iframeUrl: '/sunlight/',
        liveUrl: '/sunlight/',
        tags: ['Web App', 'Visualization'],
        description: [
            '- Sunrise, sunset, and three twilight stages with countdowns',
            '- Animated sun and moon positions, hourly moon phase',
            '- Debug time-slider for exploring the full day',
            '',
            'Pulls from Open-Meteo, Farmsense, and OpenStreetMap to render an accurate daily sky for wherever you are. Built for photographers chasing golden hour and anyone curious about local sky cycles.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/SunlightTrackerWebApp',
    },
    {
        id: 'global-time',
        title: 'Global Time & Daylight Comparison',
        summary: 'Stack multiple cities and compare their daylight side by side.',
        thumbnail: null,
        iframeUrl: '/global-time/',
        liveUrl: '/global-time/',
        tags: ['Web App', 'Visualization'],
        description: [
            '- Add any number of locations, each with its own 24-hour bar',
            '- Color-gradient backgrounds reflect live daylight phase',
            '- Live current-time markers update every minute',
            '',
            'Geocodes location names, pulls timezone and solar data, and renders synchronized day/night gradients across every bar. Handy for distributed teams and trip planning.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/TimeAndDayLightComparisonWebApp',
    },
    {
        id: 'gravity-wars',
        title: 'Gravity Wars',
        summary: 'Wave-based space shooter with roguelike ability picks.',
        thumbnail: null,
        iframeUrl: '/gravity-wars/',
        liveUrl: '/gravity-wars/',
        tags: ['Game', 'Web App'],
        description: [
            '- WASD + mouse aim, spacebar dash for repositioning',
            '- Four ability slots unlocked and upgraded between waves',
            '- Combo multiplier rewards aggressive chaining',
            '',
            'A browser arcade shooter where each run lets you cobble together an unusual build. Fast, loud, and built straight on Canvas.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/SpaceBattleGameWebApp',
    },
    {
        id: 'video-editor',
        title: 'AI Video Editor',
        summary: 'Multi-track editor with AI transcription, filler removal, and burn-in subtitles.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Tool', 'Video'],
        description: [
            '- Pause, filler-word, and profanity detection with one-click cleanup',
            '- Word-level subtitles with custom styling and burn-in',
            '- Batched FastAPI backend, ~12.5× faster than real time',
            '- GPU-accelerated FFmpeg export at multiple quality presets',
            '',
            'A complete editing surface that pairs traditional clip work with AI passes that strip out the boring parts. Designed for creators who want to ship faster without giving up control.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/VideoEditor',
    },
    {
        id: 'face-anon',
        title: 'Face Anonymization Pipeline',
        summary: 'Generate one synthetic identity, apply it consistently across video.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Video'],
        description: [
            '- RetinaFace detection with FARL anonymization',
            '- CodeFormer enhancement for realism',
            '- FaceFusion swap to apply the synthetic face to footage',
            '- GPU-accelerated, Docker-deployable end to end',
            '',
            'Solves the cross-clip continuity problem: anonymize a face once, then keep that same identity in place across an entire body of video work.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'word-extractor',
        title: 'YouTube Word Extractor',
        summary: 'Find every utterance of a word across videos and stitch them into a supercut.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Video', 'Tool'],
        description: [
            '- Six-stage pipeline: download, transcribe, search, extract, normalize, compile',
            '- Faster Whisper + CTranslate2 for word-level timestamps',
            '- Cloud cache shares transcriptions across users',
            '- GPU and CPU modes; Docker Compose deployable',
            '',
            'Point it at a video, channel, or playlist and a target word; it returns a ready-rendered compilation. Useful for compilations, research, and supercuts.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/FasterWhisperWebApp',
    },
    {
        id: 'comments',
        title: 'Production Comment System',
        summary: 'Self-hosted Discord-auth comments with AI moderation, drop in via one script tag.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Web App', 'Tool'],
        description: [
            '- Discord OAuth, no password management required',
            '- AI spam/toxicity detection plus manual moderation tools',
            '- Markdown comments, voting, reputation scores',
            '- Iframe embed auto-themes to the host site',
            '',
            'A privacy-respecting alternative to third-party comment platforms. Powers the Comments section on this very site (see the top nav).',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/CommentSectionWebApp',
    },
    {
        id: 'portfolio-v1',
        title: 'Portfolio Website (v1)',
        summary: 'The previous version of this site, built on Alpine, Tailwind, and iframe modals.',
        thumbnail: '/assets/thumbs/WYd2iPv.png',
        iframeUrl: '/v1/',
        liveUrl: '/v1/',
        tags: ['Web App', 'Personal'],
        description: [
            '- Alpine.js reactive components across eight modules',
            '- PostMessage iframe height-sync for cross-origin demos',
            '- Tailwind styling with overflow-aware filter bar',
            '',
            'The first custom build of christianblevens.me. Archived under /v1/ once the v2 deploy lands; included here for continuity.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/MyWebsite',
    },
    {
        id: 'terrain',
        title: 'Destructible Terrain',
        summary: 'Multiplayer combat where the battlefield gets carved up in real time.',
        thumbnail: '/assets/thumbs/I7ZkATK.mp4',
        iframeUrl: 'https://itch.io/embed-upload/8431679?color=333333',
        liveUrl: 'https://itch.io/embed-upload/8431679?color=333333',
        tags: ['Game', 'Multiplayer', '3D'],
        description: [
            '- Voxel terrain destruction synced across all clients',
            '- Fish Networking for authoritative multiplayer state',
            '- Data-oriented design keeps frame times flat under chaos',
            '',
            'Players carve paths and clear sightlines mid-fight while the simulation stays consistent across the network.',
        ].join('\n'),
        github: 'https://github.com/christianblevens/terrain-fighter',
    },
    {
        id: 'moba',
        title: 'Unity ECS MOBA',
        summary: 'Full-DOTS MOBA with a mod-safe, runtime-composable ability system.',
        thumbnail: '/assets/thumbs/rBJsZzW.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', 'Multiplayer', '3D'],
        description: [
            '- Pure Unity DOTS / ECS, no GameObjects in the gameplay layer',
            '- Mod-safe ability composition, networked deterministically',
            '- Steam Networking for matchmaking and lobbies',
            '',
            'Built to prove that data-oriented design and MOBA gameplay can co-exist without giving up the depth of a traditional ability system.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/UltimateMoba',
    },
    {
        id: 'tiny-home',
        title: 'Tiny Home Design Presentation',
        summary: 'Walk through tiny-home interior layouts in the browser.',
        thumbnail: '/assets/thumbs/zW5XWYm.mp4',
        iframeUrl: 'https://itch.io/embed-upload/12942892?color=333333',
        liveUrl: 'https://itch.io/embed-upload/12942892?color=333333',
        tags: ['3D', 'Business'],
        description: [
            '- ProBuilder-built interiors, no external DCC required',
            '- Modular interaction system: open cabinets, toggle features',
            '- Deployed as production WebGL for client presentations',
            '',
            'A first-person walkthrough tool that lets non-technical clients understand a space before construction starts.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'group-pathfinding',
        title: 'Group Pathfinding',
        summary: 'A* for the route, boids for the crowd, so large groups don\'t pile up.',
        thumbnail: '/assets/thumbs/9ff2MqU.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', '3D', 'Simulation'],
        description: [
            '- Two-tier: classical pathfinding for plans, boid behaviors locally',
            '- Dynamic clustering reduces per-agent path queries',
            '- Gizmo overlays for nodes, sight lines, and obstacle perception',
            '',
            'Treats moving a hundred units as a different problem than moving one. Cohesion and avoidance happen between agents while the planner handles the macro route.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'camera-radar',
        title: 'Camera + Radar Tracking',
        summary: 'University capstone: radar detects a target, a servo camera turns to face it.',
        thumbnail: '/assets/thumbs/klahjti.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Tool', 'Visualization'],
        description: [
            '- Coordinate transforms tolerate arbitrary radar/camera placement',
            '- Unity-based math validation visualizer prior to hardware deploy',
            '- Web UI for remote operation and parameter tuning',
            '',
            'Bridges sensor fusion math, embedded servo control, and a remote operator console. The visualization tool was essential; it caught coordinate-frame mistakes before they reached the hardware.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'oon-ecs',
        title: 'Object-Oriented Networking ECS',
        summary: 'A pattern that makes ECS systems first-class citizens of OOP networking libraries.',
        thumbnail: '/assets/thumbs/Rt6xMLu.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', 'Multiplayer'],
        description: [
            '- Each ECS system is wrapped as a networked object',
            '- Dynamic system-to-entity dispatch preserves DOD performance',
            '- Framework-agnostic, tested with Fish Networking',
            '',
            'Mainstream Unity multiplayer libraries assume the things on the wire are objects rather than data. This abstraction lets you use those libraries while keeping the cache and parallelism wins of ECS.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'walkable-pathfinding',
        title: 'Walkable Surface Detection',
        summary: 'Voxel-based 3D pathfinding that finds its own walkable surfaces.',
        thumbnail: '/assets/thumbs/voSAMvC.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', '3D', 'Simulation'],
        description: [
            '- Octree physics sampling discovers walkable voxels',
            '- Adjacent-node merging shrinks the navigation graph',
            '- Gizmo visualization of nodes, edges, and detected surfaces',
            '',
            'No artist-authored navmesh required. Handles overhangs, multi-level layouts, and procedurally generated environments where a baked navmesh isn\'t available.',
        ].join('\n'),
        github: null,
    },
    {
        id: '365-lighting',
        title: '365 Holiday Lighting Website',
        summary: 'Wix business site for a Christmas lighting installation company.',
        thumbnail: '/assets/thumbs/1llffvH.png',
        iframeUrl: null,
        liveUrl: 'https://www.365holidaylighting.com/',
        tags: ['Web App', 'Business'],
        description: [
            'A no-code build for a real client: services, gallery, contact, and SEO. Wix was the right tool for the job, delivering the result faster and cheaper than a custom stack would have.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'old-portfolio',
        title: 'My First Personal Website',
        summary: 'Squarespace portfolio from earlier in my career.',
        thumbnail: '/assets/thumbs/TsxhPjO.png',
        iframeUrl: '/old-portfolio/',
        liveUrl: '/old-portfolio/',
        tags: ['Web App', 'Personal'],
        description: [
            'A clean Squarespace site that served as my first online portfolio. Kept around as a milestone. The limitations of template-based platforms are what motivated the custom builds that followed.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'point-attraction',
        title: 'Point Attraction',
        summary: 'Particles with simple attraction/repulsion rules; complex behavior emerges.',
        thumbnail: '/assets/thumbs/Hjzf1Ua.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Simulation', 'Visualization'],
        description: [
            '- Per-particle pairwise attraction and repulsion',
            '- Tunable parameters expose how rule shifts change patterns',
            '',
            'Reads as fluid one moment and flocking the next, all from a handful of pairwise rules.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'tf2-dodgeball',
        title: 'TF2 Dodgeball Recreation',
        summary: 'A love letter to TF2 dodgeball with Source-style movement and added abilities.',
        thumbnail: '/assets/thumbs/UkeeOav.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game'],
        description: [
            '- Source-feel movement: air strafing, rocket jumps, momentum',
            '- Local multiplayer with rally-speed escalation',
            '- New ability set layered on top of the classic deflect mechanic',
            '',
            'Faithful to the mod that inspired it, with just enough new ideas to be its own thing.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'line-physics',
        title: 'Line Physics',
        summary: '2D physics from scratch, drawn as live line segments on canvas.',
        thumbnail: '/assets/thumbs/EIKLGGE.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Simulation'],
        description: [
            '- Gravity, velocity, constraints, and collisions, all hand-rolled',
            '- Variable resolution to trade visual fidelity for cost',
            '',
            'A learning piece that implements 2D physics by hand and makes the underlying machinery legible.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'life-sim',
        title: 'Life Simulation',
        summary: 'Agents with traits, selection pressure, and generations of drift.',
        thumbnail: '/assets/thumbs/GyREhiS.mp4',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Simulation'],
        description: [
            '- Spatial partitioning enables thousands of concurrent agents',
            '- Generational tracking of trait distributions',
            '- Query interface for inspecting subpopulations',
            '',
            'A small artificial-life sandbox where successful strategies propagate and unsuccessful ones disappear. Built with array access patterns tight enough to keep the populations large.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'van-build',
        title: 'Van Home Build',
        summary: 'Cargo van conversion: planning, leadership, and a lot of plywood.',
        thumbnail: '/assets/thumbs/eXJvpxP.jpeg',
        iframeUrl: null,
        liveUrl: null,
        tags: ['Personal'],
        description: [
            '- Long-form planning across electrical, plumbing, and structure',
            '- CAD models guided every cut and panel',
            '- Coordinated volunteers and budget across a multi-month build',
            '',
            'A real-world project run with the same discipline as a software one. Listed because the soft skills involved (scoping, decision-making, and seeing it through) are the same ones I bring to engineering work.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'voluhaus',
        title: 'Voluhaus',
        summary: 'AI-powered staging platform. See the room before the truck leaves.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: 'https://voluhaus.com/',
        tags: ['Web App', 'AI', '3D', 'Business'],
        description: [
            '- AI room extraction from a single phone photo',
            '- Drag-and-drop 3D furniture placement against the captured space',
            '- Auto-generated 3D models from photos of inventory',
            '- Inventory scheduling prevents double-booking across stagings',
            '- Shareable before/after presentations for clients',
            '',
            'A complete staging workflow for home-furnishing professionals: capture, plan, schedule, and present, all from a phone.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'random-bookmark',
        title: 'Random Bookmark Selector',
        summary: 'Break decision paralysis by pulling a random bookmark out of your saved list.',
        thumbnail: null,
        iframeUrl: '/random-bookmark/',
        liveUrl: '/random-bookmark/',
        tags: ['Web App', 'Tool'],
        description: [
            '- Paste in your bookmark export and get a random pick',
            '- Pure client-side, bookmarks never leave the page',
            '- Built straight on HTML and JS, no backend',
            '',
            'A small utility for rediscovering links you saved months ago and forgot about.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/RandomBookmarkSelector',
    },
    {
        id: 'audio-repositioner',
        title: 'Audio Repositioner',
        summary: 'Spatial audio panning in the browser. Move sound through stereo space.',
        thumbnail: null,
        iframeUrl: '/audio-repositioner/',
        liveUrl: '/audio-repositioner/',
        tags: ['Web App', 'Tool', 'Audio'],
        description: [
            '- WebAudio panner controls for left/right and depth',
            '- Drop in any audio file, no upload',
            '- Built directly on the Web Audio API',
            '',
            'A browser-native sandbox for repositioning sound in the stereo field.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/AudioRepositioner',
    },
    {
        id: 'bpd',
        title: 'Behavioral Pattern Discovery',
        summary: 'ML communication analysis that categorizes messages by behavior and pattern type.',
        thumbnail: null,
        iframeUrl: '/bpd/',
        liveUrl: '/bpd/',
        tags: ['AI', 'Web App', 'Tool', 'Visualization'],
        description: [
            '- Variational autoencoder learns the latent structure of group conversations',
            '- Categorizes messages into communication and behavior pattern types',
            '- Trained on real message exchanges between a group',
            '- Web interface for exploring the learned categories',
            '',
            'Surfaces the patterns that drive how a group actually talks. Useful for self-reflection and for understanding interpersonal dynamics that aren\'t obvious in raw transcripts.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'interactive-media-scrolling',
        title: 'Interactive Media Scrolling',
        summary: 'Three.js "cube wall" where you swipe horizontally between topics and vertically between versions.',
        thumbnail: null,
        iframeUrl: '/interactive-media-scrolling/',
        liveUrl: '/interactive-media-scrolling/',
        tags: ['Web App', '3D', 'Visualization'],
        description: [
            '- Cube-wall navigation: horizontal swipes move between cubes, vertical swipes rotate the active cube',
            '- Single-axis rotation per cube avoids the gimbal-lock issues a multi-axis cube would hit at 90°',
            '- Unified pointer pipeline with axis locking, tanh "rubber band" drag clamp, and velocity-based flick completion',
            '- Spring-physics transitions with a triangle-curve zoom-out for context on adjacent cubes',
            '- Procedural seeded content rendered directly to canvas textures on cube faces (no HTML overlays)',
            '- Draggable UI icon system with 60px grid snap, ghost preview, inventory window, and persisted positions',
            '',
            'A 3D media browser that treats cubes as the navigation primitive. Designed to feel native on both touch and mouse, with infinite horizontal scroll backed by dynamic create/destroy of off-screen cubes.',
        ].join('\n'),
        github: 'https://github.com/ChristianBlevens/InteractiveMediaScrolling',
    },
    {
        id: 'arcane-physiology',
        title: 'Arcane Physiology',
        summary: 'GPU fluid simulation as a magic system, with five immiscible "magics" flowing through spell organs.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', 'Simulation', '3D', 'Tool'],
        description: [
            '- Multi-component Lattice Boltzmann fluid sim running entirely on the GPU via wgpu compute shaders',
            '- Five magic types (Fire, Wind, Order, Earth, Chaos) with distinct mass, mobility, and Shan-Chen inter-component repulsion',
            '- Two-grid architecture: 256×256 fluid cells under a 32×32 organ-placement grid',
            '- Spell editor with seven organ categories (storage, distributor, generator, motor, sensor, projection, communication) plus a logic/signal layer for in-spell control flow',
            '- Bevy ECS extract-pipeline pattern bridges main-world editor state to render-world compute passes',
            '',
            'A working substrate for a fluid-driven magic system: organs read and write density on the GPU grid, and emergent flow defines what a spell actually does.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'roughcast',
        title: 'Roughcast (Quarry Magic)',
        summary: 'Destructible-voxel arena game with a 7-phase tournament loop and trait-driven builds.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', '3D', 'Multiplayer'],
        description: [
            '- Bevy + Rapier3D, voxel quarry and SDF colosseum as independent areas with their own primitives, chunks, and meshing',
            '- 7-phase state machine (Lobby → Generating → Dive → Build → Tournament → Victory/GameOver) with 4-round tournament progression',
            '- 12 traits with real gameplay effects: stat mods, ability swaps, berserker/vampire/x-ray, market price modifiers',
            '- Sparse-octree environmental mana with lazy decay; teleport channel, organ market, full HUD, debug console',
            '- Four enemy types under a unified state-machine + utility-scoring AI; minotaur uses GLB skeletal model with FABRIK IK',
            '- Bridges the Arcane Physiology library for organ-based spellcasting',
            '',
            'Dive into a destructible quarry to harvest organs, build spells with the fluid-magic system, then fight through the tournament. Singleplayer proof of concept of a competitive multiplayer design.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'auto-battler',
        title: 'Auto-Battler',
        summary: 'Build your fighter\'s behavior tree, recruit side guys, never control a unit directly.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', '3D', 'AI'],
        description: [
            '- Bevy + Rapier3D, point-and-click base ringed with buildings (Manor, Tavern, Store, Arena, Infirmary, Recruitment, Construction)',
            '- Player\'s main fighter runs a player-built behavior graph; recruited side guys evolve their own graphs and gear preferences',
            '- Action-based combat (Dash / Block / Projectile, plus equipment-granted actions like HeavySlam and FireBlast)',
            '- 5-stat point-buy (Strength / Agility / Vitality / Intellect / Focus) drives every derived combat value via central formulas',
            '- Magic Orb in the base renders the looping side-arena fight via a crystal-ball shader',
            '- File-per-category save/load and an in-combat graph visualizer overlay',
            '',
            'A management-first combat game: all fighter behavior is authored, never piloted. The graph builder is a real tool, not a menu.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'army-development',
        title: 'Army Development',
        summary: 'Army-scale auto-battler where soldier AI is evolved with genetic algorithms.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Game', '3D', 'AI', 'Simulation'],
        description: [
            '- Bevy ECS combat for hundreds of soldiers, with behavior trees as the unit-level AI substrate',
            '- Headless training mode runs the same combat systems offline; mutation + selection across generations against player-defined fitness expressions',
            '- Procedural branching campaign maps with 3 acts, side paths, recruitment/training/event nodes, and an Elite/Boss tier on battle nodes',
            '- Centralized combat config: every gameplay constant, archetype stat, and damage formula in one module',
            '- 18-faction design with per-region recruitable archetypes and difficulty scaling',
            '',
            'You don\'t hand-tune unit AI; you set the fitness function and let evolution find the strategy. Then you watch the result march.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'stock-sentiment',
        title: 'Stock Sentiment Predictor',
        summary: 'Transformer that fuses price history with subject-channel sentiment from news and Reddit.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Tool', 'Visualization'],
        description: [
            '- Predicts directional movement at 1-day / 1-week / 1-month horizons with calibrated confidence',
            '- Decomposes sentiment into named subject channels (e.g. "Jensen Huang", "AI chip demand") and learns per-subject importance via attention',
            '- Three pluggable sources: Finnhub (financial news), Arctic Shift (historical Reddit), PRAW (recent Reddit) with SQLite-backed gap-aware fetch tracking',
            '- Sentence-transformer embeddings + dual sentiment models (news vs social) into a Qdrant vector store, queried per-subject at train/inference time',
            '- Pre-norm transformer fuses 1D-conv-encoded price tokens with subject sentiment tokens; CLS output drives shared MLP + per-horizon delta and confidence heads',
            '- FastAPI service with lazy model loading, background-thread training, GPU AMP, and Docker deploy',
            '',
            'The hypothesis is that market-relevant sentiment is best modeled as a small set of named channels rather than a single aggregate score, and learning which channels matter for which ticker is the job of the model.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'live-censoring',
        title: 'Live Audio Censoring',
        summary: 'Real-time browser-mic profanity censor with timestamp-aligned playback ducking.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['AI', 'Web App', 'Audio', 'Tool'],
        description: [
            '- Single time domain end-to-end: frontend recording time is the reference, backend rebases SimulStreaming\'s relative timestamps onto it immediately',
            '- Word-level timestamps from streaming Whisper drive Web Audio gain automation that mutes exactly the offending word',
            '- Explicit state machines for capture, ASR, pipeline, playback, and app, with no implicit transitions or shared mutable flags',
            '- Immutable audio-chunk and transcription-result data structures with a complete audit trail from capture to playback',
            '- Auto-calibration step measures end-to-end processing delay so censor cues land on the right sample',
            '- GPU and CPU Docker images, model selection from tiny through large-v3',
            '',
            'A ground-up rework of an earlier prototype, designed to make the timing architecture correct by construction rather than by patching race conditions.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'daily-habits-android',
        title: 'Daily Habit Tracker (Android)',
        summary: 'Capacitor port of the daily-habits web app with native Android alarms and offline storage.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Web App', 'Tool', 'Mobile'],
        description: [
            '- Vanilla-JS web app wrapped with Capacitor 8 for native Android deployment, browser fallback for dev',
            '- Adaptive timeline layout: habits positioned proportionally by time-from-wake, time markers interpolated, tile object pool to keep scrolling cheap',
            '- Wake-up alarm runs as a native Android foreground service (AlarmReceiver + AlarmService) so it fires reliably with the app closed; per-habit reminders use standard notifications',
            '- Five built-in alarm tones synthesized via Web Audio oscillators (no audio files), plus custom recordings captured via MediaRecorder and stored as base64 in IndexedDB',
            '- Reactive store + custom DOM events keep feature modules loosely coupled; seven IndexedDB stores hold all state, full JSON export supported',
            '- `setup-android.js` post-install script patches AndroidManifest, MainActivity, and BridgeWebChromeClient so the WebView gets mic permission once Android grants it',
            '',
            'A native-Android port of the daily-habits web app. Same habit and streak model, with the alarm and persistence layers rebuilt against the Android runtime.',
        ].join('\n'),
        github: null,
    },
    {
        id: 'nginx-manager',
        title: 'Personal Site Infrastructure',
        summary: 'Self-hosted reverse proxy and deployment setup powering this site.',
        thumbnail: null,
        iframeUrl: null,
        liveUrl: null,
        tags: ['Tool', 'Infrastructure'],
        description: [
            '- Containerized nginx reverse proxy with SSL termination',
            '- Static asset routing with per-project cache policies',
            '- Backend service proxying with rate limiting and health checks',
            '- Drop-in config pattern for adding new projects without downtime',
            '',
            'The plumbing that lets the rest of these projects live under one domain. Private repo (it describes my server\'s internal layout), but it\'s the backbone everything else here runs on.',
        ].join('\n'),
        github: null,
    },
];

// Filter buttons are derived dynamically from the union of all tags so adding
// a new project tag automatically produces a new filter — no manual sync.
export const filters = (() => {
    const seen = new Set();
    for (const p of projects) for (const t of p.tags || []) seen.add(t);
    const tagButtons = [...seen].sort().map(t => ({ id: t, label: t }));
    return [{ id: 'all', label: 'All' }, ...tagButtons];
})();
